name: unit-tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  perl:
    name: "perl v${{ matrix.perl-version }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v3
      - run: dzil authordeps --missing |cpanm -n
      - run: dzil listdeps --develop --missing |cpanm -n
      - run: dzil smoke --author --release
